// Auto-generated record-specific 3D model configurations for all 59 Drakken records

export interface SpecimenConfig {
  scale: [number, number, number];
  primaryColor: string;
  emissiveColor: string;
  accentColor: string;
  metalness: number;
  roughness: number;
  transmission: number;
  geometryType:
    | 'basalt-pylon'
    | 'tectonic-slab'
    | 'storm-knot'
    | 'siphon-bell'
    | 'spore-pod'
    | 'mycelial-tendrils'
    | 'abyssal-hull'
    | 'fin-serpent'
    | 'wyrm-ring'
    | 'star-scaffold'
    | 'furnace-crucible'
    | 'city-moulter'
    | 'psionic-obelisk'
    | 'lattice-spire'
    | 'glitch-matrix'
    | 'null-void'
    | 'genesis-egg'
    | 'prime-matriarch';
  featureCount: number;
  animSpeed: number;
  animStyle: 'drift' | 'pulse' | 'seismic' | 'undulate' | 'spin' | 'glitch' | 'breathe';
  hasUniqueSpines?: boolean;
  hasUniqueTendrils?: boolean;
  hasUniqueFins?: boolean;
  hasUniqueRings?: boolean;
  hasUniqueMaw?: boolean;
}

export const SPECIMEN_CONFIGS: Record<string, SpecimenConfig> = {
  'skymourn': {
    scale: [2.8, 4.5, 2.8],
    primaryColor: '#b9e1f8',
    emissiveColor: '#2a5a78',
    accentColor: '#7ed6f8',
    metalness: 0.1,
    roughness: 0.2,
    transmission: 0.45,
    geometryType: 'storm-knot',
    featureCount: 8,
    animSpeed: 0.80,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'gorevault': {
    scale: [4.8, 5.6, 4.5],
    primaryColor: '#2a1417',
    emissiveColor: '#9e1a1e',
    accentColor: '#e05a2b',
    metalness: 0.4,
    roughness: 0.75,
    transmission: 0,
    geometryType: 'city-moulter',
    featureCount: 6,
    animSpeed: 0.80,
    animStyle: 'pulse',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: true,
  },
  'blood-ring': {
    scale: [1, 1, 1],
    primaryColor: '#2c2420',
    emissiveColor: '#e05a2b',
    accentColor: '#7ed6f8',
    metalness: 0.3,
    roughness: 0.6,
    transmission: 0,
    geometryType: 'basalt-pylon',
    featureCount: 6,
    animSpeed: 1.00,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'magma-pleuron': {
    scale: [2.2, 3.2, 2.2],
    primaryColor: '#1c1715',
    emissiveColor: '#e05a2b',
    accentColor: '#e05a2b',
    metalness: 0.44,
    roughness: 0.84,
    transmission: 0,
    geometryType: 'tectonic-slab',
    featureCount: 4,
    animSpeed: 0.80,
    animStyle: 'seismic',
    hasUniqueSpines: true,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'granithelion': {
    scale: [4.5, 6.2, 4.5],
    primaryColor: '#2c2420',
    emissiveColor: '#c84418',
    accentColor: '#e05a2b',
    metalness: 0.30000000000000004,
    roughness: 0.7,
    transmission: 0,
    geometryType: 'basalt-pylon',
    featureCount: 8,
    animSpeed: 1.20,
    animStyle: 'seismic',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'fault-tongue': {
    scale: [2.2, 3.2, 2.2],
    primaryColor: '#1c1715',
    emissiveColor: '#ff6b35',
    accentColor: '#e05a2b',
    metalness: 0.47000000000000003,
    roughness: 0.87,
    transmission: 0,
    geometryType: 'tectonic-slab',
    featureCount: 7,
    animSpeed: 1.10,
    animStyle: 'seismic',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'obsidian-gul': {
    scale: [3.8, 4.2, 3.2],
    primaryColor: '#2c2420',
    emissiveColor: '#e05a2b',
    accentColor: '#e05a2b',
    metalness: 0.34,
    roughness: 0.84,
    transmission: 0,
    geometryType: 'basalt-pylon',
    featureCount: 6,
    animSpeed: 1.00,
    animStyle: 'seismic',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'tremorhound': {
    scale: [2.2, 3.2, 2.2],
    primaryColor: '#1c1715',
    emissiveColor: '#c84418',
    accentColor: '#e05a2b',
    metalness: 0.2,
    roughness: 0.7,
    transmission: 0,
    geometryType: 'tectonic-slab',
    featureCount: 4,
    animSpeed: 0.80,
    animStyle: 'seismic',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'glassspine': {
    scale: [2.2, 3.2, 2.2],
    primaryColor: '#2c2420',
    emissiveColor: '#ff6b35',
    accentColor: '#e05a2b',
    metalness: 0.36,
    roughness: 0.76,
    transmission: 0,
    geometryType: 'basalt-pylon',
    featureCount: 8,
    animSpeed: 1.20,
    animStyle: 'seismic',
    hasUniqueSpines: true,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'quarrymind': {
    scale: [3.8, 4.2, 3.2],
    primaryColor: '#1c1715',
    emissiveColor: '#e05a2b',
    accentColor: '#e05a2b',
    metalness: 0.23,
    roughness: 0.73,
    transmission: 0,
    geometryType: 'tectonic-slab',
    featureCount: 7,
    animSpeed: 1.10,
    animStyle: 'seismic',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'aerokarst': {
    scale: [2.8, 4.5, 2.8],
    primaryColor: '#b9e1f8',
    emissiveColor: '#2a5a78',
    accentColor: '#7ed6f8',
    metalness: 0.1,
    roughness: 0.2,
    transmission: 0.45,
    geometryType: 'storm-knot',
    featureCount: 9,
    animSpeed: 0.90,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'hydrostatic-renderer': {
    scale: [3.5, 5.5, 3.5],
    primaryColor: '#b9e1f8',
    emissiveColor: '#7ed6f8',
    accentColor: '#7ed6f8',
    metalness: 0.1,
    roughness: 0.2,
    transmission: 0.45,
    geometryType: 'siphon-bell',
    featureCount: 15,
    animSpeed: 0.90,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'stratos-chorister': {
    scale: [2.8, 4.5, 2.8],
    primaryColor: '#b9e1f8',
    emissiveColor: '#2a5a78',
    accentColor: '#7ed6f8',
    metalness: 0.1,
    roughness: 0.2,
    transmission: 0.45,
    geometryType: 'storm-knot',
    featureCount: 15,
    animSpeed: 0.90,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'balance-engine': {
    scale: [3.5, 5.5, 3.5],
    primaryColor: '#b9e1f8',
    emissiveColor: '#7ed6f8',
    accentColor: '#7ed6f8',
    metalness: 0.1,
    roughness: 0.2,
    transmission: 0.45,
    geometryType: 'siphon-bell',
    featureCount: 15,
    animSpeed: 0.90,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'stormmind-tactician': {
    scale: [2.8, 4.5, 2.8],
    primaryColor: '#b9e1f8',
    emissiveColor: '#2a5a78',
    accentColor: '#7ed6f8',
    metalness: 0.1,
    roughness: 0.2,
    transmission: 0.45,
    geometryType: 'storm-knot',
    featureCount: 11,
    animSpeed: 1.10,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'toxic-veil-engine': {
    scale: [3.5, 5.5, 3.5],
    primaryColor: '#b9e1f8',
    emissiveColor: '#7ed6f8',
    accentColor: '#7ed6f8',
    metalness: 0.1,
    roughness: 0.2,
    transmission: 0.45,
    geometryType: 'siphon-bell',
    featureCount: 10,
    animSpeed: 1.20,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'macroflora-colossus': {
    scale: [4.2, 5, 4.2],
    primaryColor: '#4a6b38',
    emissiveColor: '#7ed6f8',
    accentColor: '#4a6b38',
    metalness: 0.15,
    roughness: 0.6,
    transmission: 0,
    geometryType: 'spore-pod',
    featureCount: 10,
    animSpeed: 0.90,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: true,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'sporesphere-archivist': {
    scale: [2.5, 3.5, 2.5],
    primaryColor: '#2a401c',
    emissiveColor: '#7ed6f8',
    accentColor: '#4a6b38',
    metalness: 0.15,
    roughness: 0.6,
    transmission: 0,
    geometryType: 'mycelial-tendrils',
    featureCount: 10,
    animSpeed: 1.20,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: true,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'neural-fungibinder': {
    scale: [2.5, 3.5, 2.5],
    primaryColor: '#4a6b38',
    emissiveColor: '#7ed6f8',
    accentColor: '#4a6b38',
    metalness: 0.15,
    roughness: 0.6,
    transmission: 0,
    geometryType: 'spore-pod',
    featureCount: 6,
    animSpeed: 1.20,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: true,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'precipitation-synth': {
    scale: [2.5, 3.5, 2.5],
    primaryColor: '#2a401c',
    emissiveColor: '#7ed6f8',
    accentColor: '#4a6b38',
    metalness: 0.15,
    roughness: 0.6,
    transmission: 0,
    geometryType: 'mycelial-tendrils',
    featureCount: 10,
    animSpeed: 0.80,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: true,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'soil-rewriter': {
    scale: [4.2, 5, 4.2],
    primaryColor: '#4a6b38',
    emissiveColor: '#7ed6f8',
    accentColor: '#4a6b38',
    metalness: 0.15,
    roughness: 0.6,
    transmission: 0,
    geometryType: 'spore-pod',
    featureCount: 6,
    animSpeed: 0.90,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: true,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'hive-floramother': {
    scale: [4.2, 5, 4.2],
    primaryColor: '#2a401c',
    emissiveColor: '#7ed6f8',
    accentColor: '#4a6b38',
    metalness: 0.15,
    roughness: 0.6,
    transmission: 0,
    geometryType: 'mycelial-tendrils',
    featureCount: 9,
    animSpeed: 1.30,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: true,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'trench-sovereign': {
    scale: [2.6, 4.8, 2.2],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'abyssal-hull',
    featureCount: 8,
    animSpeed: 1.20,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'salinity-conductor': {
    scale: [2.6, 4.8, 2.2],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'fin-serpent',
    featureCount: 5,
    animSpeed: 0.90,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'gyre-tactician': {
    scale: [2.6, 4.8, 2.2],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'abyssal-hull',
    featureCount: 4,
    animSpeed: 0.80,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'littoral-reformer': {
    scale: [4.5, 6, 3.5],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'fin-serpent',
    featureCount: 8,
    animSpeed: 1.20,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'cryofluid-engine': {
    scale: [2.6, 4.8, 2.2],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'abyssal-hull',
    featureCount: 6,
    animSpeed: 1.00,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'nebular-stream-herder': {
    scale: [4.5, 6, 3.5],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'fin-serpent',
    featureCount: 8,
    animSpeed: 1.20,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'stellar-plasma-swimmer': {
    scale: [2.6, 4.8, 2.2],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'abyssal-hull',
    featureCount: 8,
    animSpeed: 1.20,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'orbital-extrusion-engine': {
    scale: [4.5, 6, 3.5],
    primaryColor: '#1e405b',
    emissiveColor: '#0e2334',
    accentColor: '#7ed6f8',
    metalness: 0.35,
    roughness: 0.25,
    transmission: 0.3,
    geometryType: 'fin-serpent',
    featureCount: 5,
    animSpeed: 0.90,
    animStyle: 'undulate',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: true,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'starbinder-core': {
    scale: [5.2, 5.2, 5.2],
    primaryColor: '#7a0e1c',
    emissiveColor: '#640812',
    accentColor: '#c4a359',
    metalness: 0.75,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'wyrm-ring',
    featureCount: 17,
    animSpeed: 1.10,
    animStyle: 'spin',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'gravity-impaler': {
    scale: [5.2, 5.2, 5.2],
    primaryColor: '#7a0e1c',
    emissiveColor: '#640812',
    accentColor: '#c4a359',
    metalness: 0.75,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'star-scaffold',
    featureCount: 14,
    animSpeed: 1.00,
    animStyle: 'spin',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'deepsong-carrier': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#7a0e1c',
    emissiveColor: '#640812',
    accentColor: '#c4a359',
    metalness: 0.75,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'wyrm-ring',
    featureCount: 12,
    animSpeed: 1.20,
    animStyle: 'spin',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'radiant-scaffold': {
    scale: [5.2, 5.2, 5.2],
    primaryColor: '#7a0e1c',
    emissiveColor: '#640812',
    accentColor: '#c4a359',
    metalness: 0.75,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'star-scaffold',
    featureCount: 19,
    animSpeed: 1.10,
    animStyle: 'spin',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'phantom-occluder': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#7a0e1c',
    emissiveColor: '#640812',
    accentColor: '#c4a359',
    metalness: 0.75,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'wyrm-ring',
    featureCount: 16,
    animSpeed: 1.00,
    animStyle: 'spin',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'burnline-reaper': {
    scale: [5.2, 5.2, 5.2],
    primaryColor: '#7a0e1c',
    emissiveColor: '#640812',
    accentColor: '#c4a359',
    metalness: 0.75,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'star-scaffold',
    featureCount: 12,
    animSpeed: 0.80,
    animStyle: 'spin',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'data-core-unbinder': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#7a0e1c',
    emissiveColor: '#640812',
    accentColor: '#c4a359',
    metalness: 0.75,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'wyrm-ring',
    featureCount: 12,
    animSpeed: 1.20,
    animStyle: 'spin',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'foundry-cantor': {
    scale: [4.8, 5.6, 4.5],
    primaryColor: '#2a1417',
    emissiveColor: '#9e1a1e',
    accentColor: '#e05a2b',
    metalness: 0.4,
    roughness: 0.75,
    transmission: 0,
    geometryType: 'city-moulter',
    featureCount: 9,
    animSpeed: 1.10,
    animStyle: 'pulse',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: true,
  },
  'power-lattice-regulator': {
    scale: [4.8, 5.6, 4.5],
    primaryColor: '#2a1417',
    emissiveColor: '#9e1a1e',
    accentColor: '#e05a2b',
    metalness: 0.4,
    roughness: 0.75,
    transmission: 0,
    geometryType: 'furnace-crucible',
    featureCount: 11,
    animSpeed: 1.30,
    animStyle: 'pulse',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: true,
  },
  'skyline-moulter': {
    scale: [4.8, 5.6, 4.5],
    primaryColor: '#2a1417',
    emissiveColor: '#9e1a1e',
    accentColor: '#e05a2b',
    metalness: 0.4,
    roughness: 0.75,
    transmission: 0,
    geometryType: 'city-moulter',
    featureCount: 10,
    animSpeed: 1.20,
    animStyle: 'pulse',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: true,
  },
  'transit-impaler': {
    scale: [3.2, 3.8, 3.2],
    primaryColor: '#2a1417',
    emissiveColor: '#9e1a1e',
    accentColor: '#e05a2b',
    metalness: 0.4,
    roughness: 0.75,
    transmission: 0,
    geometryType: 'furnace-crucible',
    featureCount: 9,
    animSpeed: 1.10,
    animStyle: 'pulse',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: true,
  },
  'demographic-planner': {
    scale: [4.8, 5.6, 4.5],
    primaryColor: '#2a1417',
    emissiveColor: '#9e1a1e',
    accentColor: '#e05a2b',
    metalness: 0.4,
    roughness: 0.75,
    transmission: 0,
    geometryType: 'city-moulter',
    featureCount: 8,
    animSpeed: 1.00,
    animStyle: 'pulse',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: true,
  },
  'record-devourer': {
    scale: [3.2, 3.8, 3.2],
    primaryColor: '#2a1417',
    emissiveColor: '#9e1a1e',
    accentColor: '#e05a2b',
    metalness: 0.4,
    roughness: 0.75,
    transmission: 0,
    geometryType: 'furnace-crucible',
    featureCount: 7,
    animSpeed: 0.90,
    animStyle: 'pulse',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: true,
  },
  'syntax-breaker': {
    scale: [2.4, 5.2, 2.4],
    primaryColor: '#8a85b6',
    emissiveColor: '#4d4778',
    accentColor: '#8a85b6',
    metalness: 0.2,
    roughness: 0.15,
    transmission: 0.5,
    geometryType: 'lattice-spire',
    featureCount: 3,
    animSpeed: 1.30,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'civic-time-rewriter': {
    scale: [2.4, 5.2, 2.4],
    primaryColor: '#8a85b6',
    emissiveColor: '#4d4778',
    accentColor: '#8a85b6',
    metalness: 0.2,
    roughness: 0.15,
    transmission: 0.5,
    geometryType: 'psionic-obelisk',
    featureCount: 5,
    animSpeed: 0.90,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'oneiric-ecologist': {
    scale: [2.4, 5.2, 2.4],
    primaryColor: '#8a85b6',
    emissiveColor: '#4d4778',
    accentColor: '#8a85b6',
    metalness: 0.2,
    roughness: 0.15,
    transmission: 0.5,
    geometryType: 'lattice-spire',
    featureCount: 5,
    animSpeed: 1.00,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'sovereignty-eater': {
    scale: [2.4, 5.2, 2.4],
    primaryColor: '#8a85b6',
    emissiveColor: '#4d4778',
    accentColor: '#8a85b6',
    metalness: 0.2,
    roughness: 0.15,
    transmission: 0.5,
    geometryType: 'psionic-obelisk',
    featureCount: 7,
    animSpeed: 1.10,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'hymnlock': {
    scale: [2.4, 5.2, 2.4],
    primaryColor: '#8a85b6',
    emissiveColor: '#4d4778',
    accentColor: '#8a85b6',
    metalness: 0.2,
    roughness: 0.15,
    transmission: 0.5,
    geometryType: 'lattice-spire',
    featureCount: 5,
    animSpeed: 1.30,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'memorialvein': {
    scale: [2.4, 5.2, 2.4],
    primaryColor: '#8a85b6',
    emissiveColor: '#4d4778',
    accentColor: '#8a85b6',
    metalness: 0.2,
    roughness: 0.15,
    transmission: 0.5,
    geometryType: 'psionic-obelisk',
    featureCount: 6,
    animSpeed: 1.20,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'shrinehunger': {
    scale: [2.4, 5.2, 2.4],
    primaryColor: '#8a85b6',
    emissiveColor: '#4d4778',
    accentColor: '#8a85b6',
    metalness: 0.2,
    roughness: 0.15,
    transmission: 0.5,
    geometryType: 'lattice-spire',
    featureCount: 3,
    animSpeed: 1.30,
    animStyle: 'drift',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: true,
    hasUniqueMaw: false,
  },
  'redacted-grin': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#e05a2b',
    emissiveColor: '#a83812',
    accentColor: '#7ed6f8',
    metalness: 0.5,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'glitch-matrix',
    featureCount: 5,
    animSpeed: 1.30,
    animStyle: 'glitch',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'spinal-loop': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#e05a2b',
    emissiveColor: '#a83812',
    accentColor: '#7ed6f8',
    metalness: 0.5,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'null-void',
    featureCount: 4,
    animSpeed: 1.00,
    animStyle: 'glitch',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'cradle-exe': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#e05a2b',
    emissiveColor: '#a83812',
    accentColor: '#7ed6f8',
    metalness: 0.5,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'glitch-matrix',
    featureCount: 6,
    animSpeed: 1.20,
    animStyle: 'glitch',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'foldhowl': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#e05a2b',
    emissiveColor: '#a83812',
    accentColor: '#7ed6f8',
    metalness: 0.5,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'null-void',
    featureCount: 5,
    animSpeed: 0.90,
    animStyle: 'glitch',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'manifest-discord': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#e05a2b',
    emissiveColor: '#a83812',
    accentColor: '#7ed6f8',
    metalness: 0.5,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'glitch-matrix',
    featureCount: 6,
    animSpeed: 1.00,
    animStyle: 'glitch',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'gloryfail': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#e05a2b',
    emissiveColor: '#a83812',
    accentColor: '#7ed6f8',
    metalness: 0.5,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'null-void',
    featureCount: 6,
    animSpeed: 1.00,
    animStyle: 'glitch',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'viral-bastion': {
    scale: [3.2, 3.2, 3.2],
    primaryColor: '#e05a2b',
    emissiveColor: '#a83812',
    accentColor: '#7ed6f8',
    metalness: 0.5,
    roughness: 0.2,
    transmission: 0,
    geometryType: 'glitch-matrix',
    featureCount: 7,
    animSpeed: 0.90,
    animStyle: 'glitch',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'mother': {
    scale: [4.5, 6.5, 4.5],
    primaryColor: '#f0f8ff',
    emissiveColor: '#c4a359',
    accentColor: '#c4a359',
    metalness: 0.8,
    roughness: 0.1,
    transmission: 0.65,
    geometryType: 'prime-matriarch',
    featureCount: 6,
    animSpeed: 0.90,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
  'the-egg': {
    scale: [3.6, 4.8, 3.6],
    primaryColor: '#f0f8ff',
    emissiveColor: '#c4a359',
    accentColor: '#c4a359',
    metalness: 0.8,
    roughness: 0.1,
    transmission: 0.65,
    geometryType: 'genesis-egg',
    featureCount: 6,
    animSpeed: 1.10,
    animStyle: 'breathe',
    hasUniqueSpines: false,
    hasUniqueTendrils: false,
    hasUniqueFins: false,
    hasUniqueRings: false,
    hasUniqueMaw: false,
  },
};
