export const POLISH_WAVE_3_IMPROVEMENTS = [
  { id: 'W3-01', title: 'Declare a coherent dark native-control color scheme' },
  { id: 'W3-02', title: 'Use a consistent accent and caret color across controls' },
  { id: 'W3-03', title: 'Remove distracting tap flashes without weakening focus feedback' },
  { id: 'W3-04', title: 'Separate selectable archive content from nonselectable control chrome' },
  { id: 'W3-05', title: 'Standardize visible keyboard focus across interactive surfaces' },
  { id: 'W3-06', title: 'Refine keyboard shortcut keycap typography and contrast' },
  { id: 'W3-07', title: 'Use stable tabular numerals for identifiers, metrics, and outputs' },
  { id: 'W3-08', title: 'Give archive identifiers a consistent technical typographic treatment' },
  { id: 'W3-09', title: 'Add non-color evidence-state markers to evidence badges' },
  { id: 'W3-10', title: 'Improve long dossier copy wrapping and hyphenation' },
  { id: 'W3-11', title: 'Constrain long-form reading width inside record surfaces' },
  { id: 'W3-12', title: 'Make source references readable and safely wrappable' },
  { id: 'W3-13', title: 'Improve record-grid scan rhythm and term-value separation' },
  { id: 'W3-14', title: 'Strengthen annotation-detail hierarchy with a stable evidence rail' },
  { id: 'W3-15', title: 'Give annotation rows keyboard-focus parity with pointer hover' },
  { id: 'W3-16', title: 'Add useful scroll margins for selected records and sections' },
  { id: 'W3-17', title: 'Reserve drawer scroll padding around sticky chrome and actions' },
  { id: 'W3-18', title: 'Refine sticky heading edge separation during drawer scrolling' },
  { id: 'W3-19', title: 'Give specimen cards consistent hover and focus-visible elevation' },
  { id: 'W3-20', title: 'Refine active-mode chips for rapid scanning' },
  { id: 'W3-21', title: 'Improve status-toast wrapping and visual timing feedback' },
  { id: 'W3-22', title: 'Clarify loading progress without increasing overlay density' },
  { id: 'W3-23', title: 'Differentiate primary and secondary error recovery actions' },
  { id: 'W3-24', title: 'Number orientation topics for faster briefing scanning' },
  { id: 'W3-25', title: 'Equalize orientation-card item height and internal rhythm' },
  { id: 'W3-26', title: 'Refine record-tab overflow affordance and selected-state depth' },
  { id: 'W3-27', title: 'Present live tool outputs as compact technical readouts' },
  { id: 'W3-28', title: 'Improve select-field truncation and minimum readable width' },
  { id: 'W3-29', title: 'Compact drawers responsibly on short desktop viewports' },
  { id: 'W3-30', title: 'Improve landscape-mobile tools-sheet height and scrolling' },
  { id: 'W3-31', title: 'Protect ultra-narrow mobile controls from horizontal clipping' },
  { id: 'W3-32', title: 'Reduce decorative surface cost when the device requests reduced data' },
] as const;
