export const POLISH_WAVE_4_IMPROVEMENTS = [
  { id: 'W4-01', title: 'Standardize transition rhythm across compact interactive controls' },
  { id: 'W4-02', title: 'Add tactile pressed feedback without layout movement' },
  { id: 'W4-03', title: 'Use honest disabled cursor and text treatment' },
  { id: 'W4-04', title: 'Advertise enabled interactive controls with appropriate cursors' },
  { id: 'W4-05', title: 'Unify component-level focus halos' },
  { id: 'W4-06', title: 'Refine the skip link into a clear keyboard escape route' },
  { id: 'W4-07', title: 'Clarify the drawer scrim as a dismiss surface' },
  { id: 'W4-08', title: 'Standardize modal close-control geometry' },
  { id: 'W4-09', title: 'Improve panel-heading action alignment and spacing' },
  { id: 'W4-10', title: 'Add restrained drawer-heading depth separation' },
  { id: 'W4-11', title: 'Strengthen Registry field-label hierarchy' },
  { id: 'W4-12', title: 'Improve Registry search placeholder contrast' },
  { id: 'W4-13', title: 'Differentiate idle and focused search borders' },
  { id: 'W4-14', title: 'Enlarge the clear-search hit area without visual bulk' },
  { id: 'W4-15', title: 'Normalize filter-row wrap rhythm' },
  { id: 'W4-16', title: 'Stabilize filter-chip height and padding' },
  { id: 'W4-17', title: 'Give active filters a non-color selected treatment' },
  { id: 'W4-18', title: 'Separate Registry result count from reset action' },
  { id: 'W4-19', title: 'Improve specimen-card internal spacing rhythm' },
  { id: 'W4-20', title: 'Add a quiet active-specimen inner frame' },
  { id: 'W4-21', title: 'Separate specimen designation from archive identifier' },
  { id: 'W4-22', title: 'Present archive IDs as compact technical capsules' },
  { id: 'W4-23', title: 'Align specimen metadata as readable paired rows' },
  { id: 'W4-24', title: 'Strengthen threat and availability value emphasis' },
  { id: 'W4-25', title: 'Separate evidence badges from source-status copy' },
  { id: 'W4-26', title: 'Make the empty-state reset action unmistakable' },
  { id: 'W4-27', title: 'Refine Tools reset as a visible secondary action' },
  { id: 'W4-28', title: 'Arrange primary tool clusters in a responsive grid' },
  { id: 'W4-29', title: 'Add a technical rail to tool-cluster headings' },
  { id: 'W4-30', title: 'Stabilize tool-control heights' },
  { id: 'W4-31', title: 'Make pressed toggles appear physically engaged' },
  { id: 'W4-32', title: 'Refine axis controls as a compact segmented group' },
  { id: 'W4-33', title: 'Present layer toggles as complete anatomy cards' },
  { id: 'W4-34', title: 'Protect secondary layer descriptions from overflow' },
  { id: 'W4-35', title: 'Add a non-color active rail to visible anatomy layers' },
  { id: 'W4-36', title: 'Align range labels with live output values' },
  { id: 'W4-37', title: 'Improve slider hover and focus manipulation feedback' },
  { id: 'W4-38', title: 'Unify select-field focus treatment with Registry search' },
  { id: 'W4-39', title: 'Normalize wrapping and spacing in action rows' },
  { id: 'W4-40', title: 'Present measurement guidance as a technical readout' },
  { id: 'W4-41', title: 'Contain the active-mode rail without creating a toolbar' },
  { id: 'W4-42', title: 'Separate record evidence status from descriptive prose' },
  { id: 'W4-43', title: 'Strengthen selected record-tab hierarchy' },
  { id: 'W4-44', title: 'Give record content a reliable opening rhythm' },
  { id: 'W4-45', title: 'Standardize term-value card alignment' },
  { id: 'W4-46', title: 'Improve visual distinction between record labels and values' },
  { id: 'W4-47', title: 'Normalize dossier article heading and ending rhythm' },
  { id: 'W4-48', title: 'Add a restrained civic-response section accent' },
  { id: 'W4-49', title: 'Number source cards for scan order' },
  { id: 'W4-50', title: 'Establish a clear annotation-section boundary' },
  { id: 'W4-51', title: 'Refine annotation utility actions' },
  { id: 'W4-52', title: 'Make annotation export inclusion unambiguous' },
  { id: 'W4-53', title: 'Structure annotation metadata as a readable grid' },
  { id: 'W4-54', title: 'Present export actions as the dossier completion group' },
  { id: 'W4-55', title: 'Add subtle Diagnostics row striping for scan speed' },
  { id: 'W4-56', title: 'Add a classified-document accent to the briefing' },
  { id: 'W4-57', title: 'Strengthen the briefing acknowledgement action' },
  { id: 'W4-58', title: 'Clarify loading and error overlay action hierarchy' },
  { id: 'W4-59', title: 'Keep status feedback clear of viewport safe areas' },
  { id: 'W4-60', title: 'Protect constrained devices and accessibility preferences' },
] as const;

export const POLISH_WAVE_4_REPAIRS: ReadonlyArray<{ id: string; title: string }> = [];
