export const POLISH_WAVE_2_IMPROVEMENTS = [
  { id: 'W2-01', title: 'Use a high-legibility archive text selection treatment' },
  { id: 'W2-02', title: 'Introduce restrained raised-surface and glow finish tokens' },
  { id: 'W2-03', title: 'Balance display headings without disturbing body-copy width' },
  { id: 'W2-04', title: 'Improve long-form dossier paragraph wrapping' },
  { id: 'W2-05', title: 'Add a precise inner edge to every modal drawer surface' },
  { id: 'W2-06', title: 'Refine drawer scrollbar tracks, thumbs, and hover feedback' },
  { id: 'W2-07', title: 'Strengthen sticky drawer heading separation and depth' },
  { id: 'W2-08', title: 'Polish circular close controls and focus feedback' },
  { id: 'W2-09', title: 'Add a leading visual search affordance' },
  { id: 'W2-10', title: 'Give registry search a clear focus-within state' },
  { id: 'W2-11', title: 'Polish the search clear micro-control' },
  { id: 'W2-12', title: 'Separate filter groups with quiet archival dividers' },
  { id: 'W2-13', title: 'Refine filter chips into deliberate segmented tags' },
  { id: 'W2-14', title: 'Give the registry summary a stable depth boundary' },
  { id: 'W2-15', title: 'Increase registry result rhythm and lower padding' },
  { id: 'W2-16', title: 'Add controlled elevation and material depth to specimen cards' },
  { id: 'W2-17', title: 'Add a luminous active-record edge marker' },
  { id: 'W2-18', title: 'Prevent card metadata and source labels from breaking layout' },
  { id: 'W2-19', title: 'Refine pending-record pulse feedback' },
  { id: 'W2-20', title: 'Give the empty registry state a purposeful visual anchor' },
  { id: 'W2-21', title: 'Refine the tools-sheet grab handle' },
  { id: 'W2-22', title: 'Group primary camera and render controls as compact surfaces' },
  { id: 'W2-23', title: 'Increase tool-panel hierarchy and focus-within clarity' },
  { id: 'W2-24', title: 'Provide custom range tracks and precise slider thumbs' },
  { id: 'W2-25', title: 'Provide a consistent custom select chevron' },
  { id: 'W2-26', title: 'Make disabled controls visibly intentional' },
  { id: 'W2-27', title: 'Add stable active-state markers without relying on color alone' },
  { id: 'W2-28', title: 'Refine the active examination-mode rail' },
  { id: 'W2-29', title: 'Polish record tabs as a compact segmented navigator' },
  { id: 'W2-30', title: 'Give dossier records, incidents, civic notes, and sources card surfaces' },
  { id: 'W2-31', title: 'Improve annotation row hover, active, and detail hierarchy' },
  { id: 'W2-32', title: 'Pin export actions to a clear drawer footer' },
  { id: 'W2-33', title: 'Align diagnostics labels and numeric values for scanning' },
  { id: 'W2-34', title: 'Add a restrained status-toast lifetime indicator' },
  { id: 'W2-35', title: 'Add polished loading shimmer and error severity accents' },
  { id: 'W2-36', title: 'Refine briefing card depth and orientation-item surfaces' },
  { id: 'W2-37', title: 'Add mobile record-tab scroll snapping' },
  { id: 'W2-38', title: 'Compact mobile specimen cards without losing identity' },
  { id: 'W2-39', title: 'Refine mobile tools spacing and panel radii' },
] as const;

export const POLISH_WAVE_2_REPAIRS = [
  { id: 'W2-A01', title: 'Load the existing legibility layer that was present but orphaned' },
  { id: 'W2-A02', title: 'Reserve content space beneath the sticky export footer' },
  { id: 'W2-A03', title: 'Anchor active-state dots without changing button width' },
  { id: 'W2-A04', title: 'Remove hover lift and enlarge micro-controls on coarse pointers' },
  { id: 'W2-A05', title: 'Release sticky record chrome on very narrow mobile viewports' },
  { id: 'W2-A06', title: 'Disable decorative motion under reduced-motion preferences' },
  { id: 'W2-A07', title: 'Provide opaque surfaces for reduced-transparency preferences' },
  { id: 'W2-A08', title: 'Increase borders and muted-text contrast when more contrast is requested' },
  { id: 'W2-A09', title: 'Restore native system colors and controls in forced-colors mode' },
] as const;
